# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            - npm-v1-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - npm-v1-
      - run:
          name: npm install
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: # run tests
          name: run tests
          command: npm run ci

      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results.xml
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml

      - run:
          name: release
          command: npm run semantic-release || true

  docs:
    docker:
      - image: circleci/ruby:2.7.1-buster-node
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:40:36:ee:3c:52:25:dd:c7:41:f3:10:d1:ce:f9:33"
      - checkout
      - run:
          name: checkout repo and submodules
          command: git submodule update --init --recursive
      - run:
          name: bundler version
          command: bundle -v
      - run:
          name: ruby version
          command: ruby -v
      - run:
          name: node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v

      - run: sudo apt-get update

      - run:
          name: graphviz for dot diagrams
          command: sudo apt-get -qq -y install graphviz

      - run:
          name: Bundle Install.pre - needed for mathematical -> 'asciidoctor-mathematical' gem
          command: sudo apt-get -qq -y install cmake bison flex libffi-dev libxml2-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev

      - run:
          name: Bundle Install.pre - install GraphicsMagick for 'prawn-gmagick' gem
          command: sudo apt-get -qq -y install graphicsmagick-imagemagick-compat graphicsmagick-libmagick-dev-compat

      # Restore bundle cache
      - restore_cache:
          keys:
            - gemfile-v1-{{ checksum "book/config/Gemfile.lock" }}
            - gemfile-v1-

      - run:
          name: Bundle Install
          command: cd book/config && bundle check --path vendor/bundle || ( bundle install --path vendor/bundle )

      # Store bundle cache
      - save_cache:
          key: gemfile-v1-{{ checksum "book/config/Gemfile.lock" }}
          paths:
            - book/config/vendor/bundle

      - run:
          name: generate PDF
          command: cd book/config && make VERSION="$(npx -c 'echo "$npm_package_version"')"

      - store_artifacts:
          path: book/dist
          destination: book

workflows:
  version: 2
  build_and_docs:
    jobs:
      - build
      - docs
